baseURL: "https://profound-nougat-2ec5fa.netlify.app"
languageCode: "en-gb"
title: "Daniel Gibbs"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Daniel Gibbs"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/anchor.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Daniel Gibbs" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: true
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Daniel Gibbs"
    subtitle: "Platform and Linux Engineer"
    content: "Ex Royal Navy Engineer, Plaform Engineer, Linux Enthusiast and Developer of LinuxGSM."
    image: /images/avatar_background.png
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/dgibbs64
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/dgibbs64/
      customIcons:
        - icon: /images/LinuxGSM_avatar_v2_512.jpg
          url: https://linuxgsm.com

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/avatar-23-512-nobg.png"
    content: |-
      I am a Platform Engineer and Armed Forces Veteran with a specialty in server operations and Linux. I am also the lead developer of LinuxGSM, an open-source project for managing game servers.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Ansible"
        - "BASH"
        - "CentOS"
        - "Cloudflare"
        - "Docker"
        - "Github Actions"
        - "Terraform"
        - "Ubuntu"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Senior Platform Engineer"
        company: "Phoenix Group"
        companyUrl: "https://www.thephoenixgroup.com/"
        date: "Jan 2023 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "DevOps Engineer"
        company: "OGL Software"
        companyUrl: "https://ogl.co.uk"
        date: "Aug 2021 - Dec 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
        content: |
          My goal was to help the web and Linux teams work more efficiently and effectively by using automation and industry-standard practices, and by collaborating with other departments and developers to utilize our diverse skills and expertise to drive improvements and achieve our objectives.
          - Using automation tools like Ansible and terraform to streamline the deployment process for web servers such as Apache and Nginx.
          - Maintaining and integrating a Zabbix monitoring solution.
          - Improving and educating on DevOps processes and advocating for new tooling.
          - Maintaining a custom server deployment and inventory tool.
          - Managing Cloudflare tenants and git repositories on BitBucket.
      - job: "Combat Systems Engineer"
        company: "BAE Systems"
        companyUrl: "https://www.baesystems.com/en-uk/home"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://www.baesystems.com/en-uk/home"
        content: |
          Over the course of three years, I have held multiple IT-based roles within BAE Systems. My career with the company began with me installing network equipment on board HMS Prince of Wales before becoming a Combat Systems engineer. In this role, I conducted trials and wrote "Body of Evidence" reports to ensure the product was safe and functional for installation. I also worked on another project, supporting the integration and trials. This included installing cabling infrastructure and clients, maintaining and administering the representative test environment, creating a solution to gather performance metrics, and supporting trial engineers to allow hosted trials to be conducted.
      - job: "Weapon Engineer"
        company: "Royal Navy"
        companyUrl: "https://www.royalnavy.mod.uk/"
        date: "Feb 2014 - Jul 2018"
        featuredLink:
          enable: true
          name: "Herbert Lott Award"
          url: "https://www.royalnavy.mod.uk/news-and-latest-activity/news/2017/october/25/171025-weapons-engineer-wins-top-innovation-award"
        content: |
          I have 4 years of experience as a Weapon Engineer in the Royal Navy, serving on three of the latest warships and working on various communication systems such as ship-based computer networks, self-powered telephones, and broadcast & alarm systems. I have a strong background in the networks section, where I designed a user-friendly graphical interface for the QEC network management system that made an advanced system easy to understand for non-technical personnel. My efforts were recognized with two awards, the Herbert Lott and CO's Efficiency Award.
  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: LinuxGSM
        content: The command-line tool for quick, simple deployment and management of Linux dedicated game servers.
        image: /images/projects/linuxgsm.jpg
        featured:
          name: Project Website
          link: https://linuxgsm.com
        badges:
          - "BASH"
          - "Game Servers"
          - "Linux"
        links:
          - icon: fab fa-github
            url: https://github.com/GameServerManagers/LinuxGSM

      - title: Ansible Roles
        content: I have created number of Ansible roles.
        image: /images/projects/ansible.jpg
        featured:
          name: Ansible Galaxy
          link: https://galaxy.ansible.com/dgibbs64
        badges:
          - "Ansible"
          - "Galaxy"
          - "Molecule"
        links:
          - icon: fab fa-github
            url: https://github.com/dgibbs64?tab=repositories&q=ansible

      - title: Wordpress Site
        content: Recently completed a website for a local car club.
        image: /images/projects/wordpress.png
        featured:
          name: Website
          link: https://kiddycar.club
        badges:
          - "Wordpress"
          - "Bootstrap"

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
